export function createPageUrl(pageName) {
  const routeMap = {
    'Home': '/',
    'TradingFloor': '/overview',
    'Equities': '/equities',
    'FixedIncome': '/fixed-income',
    'Options': '/options',
    'Positions': '/positions',
    'RiskAnalytics': '/risk-analytics',
    'AIInsights': '/ai-insights',
    'Macro': '/macro',
    'Credit': '/credit',
    'Commodities': '/commodities',
    'FX': '/fx',
    'Asia': '/asia',
    'EU': '/eu',
    'US': '/us',
    'AllInsights': '/all-insights',
    'PortfolioOptimizer': '/portfolio-optimizer',
    'SentimentAnalytics': '/sentiment-analytics',
    'ESGAnalytics': '/esg-analytics',
    'TradeExecution': '/trade-execution',
    'CompsScreener': '/comps-screener',
    'StrategyBacktesting': '/strategy-backtesting',
    'AIStrategyGenerator': '/ai-strategy-generator',
    'AlternativeData': '/alternative-data',
    'MarketMicrostructure': '/market-microstructure',
    'StatisticalArbitrage': '/statistical-arbitrage',
    'RegulatoryAnalyzer': '/regulatory-analyzer',
    'CompanyImpactAssessment': '/company-impact-assessment',
    'PortfolioDashboard': '/portfolio-dashboard',
    'ScenarioSimulator': '/scenario-simulator',
    'RecommendationsEngine': '/recommendations-engine',
    'TenKIntelligence': '/tenk-intelligence',
    'NLPQuantStrategy': '/nlp-quant-strategy',
    'AdaptabilityDemo': '/adaptability-demo',
    'LawsuitTracker': '/lawsuit-tracker',
    'TrendsAnalysis': '/trends-analysis',
    'SocialSentiment': '/social-sentiment',
    'RegulatoryImpact': '/regulatory-impact',
  };
  
  return routeMap[pageName] || '/';
}

